name: GitHub Actions Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build
        run: npm install && npm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          repository-name: zhrren/json2ts
          branch: gh-pages
          folder: build
